### ISSUE TITLE
Withdrawal Method Plugin Incompatibility with Dokan Marketplace

### ISSUE THREAD

**Issue by maliktanveerdhool** [BeycanPress/cryptopay-withdrawal-for-dokan#2]
I am writing to bring to your attention a critical issue regarding the withdrawal method. Currently, this method is not active and does not function correctly within the Dokan Marketplace framework. This incompatibility is significantly impacting our ability to process withdrawals efficiently and is causing considerable inconvenience to our users.

We rely on your plugin for seamless financial transactions, and this disruption is affecting our operations. We kindly request that you investigate this issue as a priority and provide a timely resolution. If additional information or collaboration is required from our end, please do not hesitate to let us know.
![image](https://github.com/BeycanPress/cryptopay-withdrawal-for-dokan/assets/53822107/385ac32c-707f-49e9-8c43-df0c6e62725b)

**Comment by 0xBeycan** [comment]
Hello, this problem has been fixed and the issue has been closed.
